name: Build Artifacts for PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  REPO_NAME_OLD: rudderlabs/develop-rudder-transformer
  REPO_NAME: rudderstack/develop-rudder-transformer
  DOCKERHUB_USERNAME: rudderlabs

jobs:
  generate-tag-name:
    name: Generate Tag Name
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.gen_tag_name.outputs.tag_name }}
    steps:
      # Replace problematic characters in branch name (like '/') with safe characters (like '.')
      - name: Generate Tag Name
        id: gen_tag_name
        shell: bash
        run: |
          echo "tag_name=$(echo ${{ github.head_ref }} | tr "/" .)" >> $GITHUB_OUTPUT

  build-transformer-image:
    name: Build Transformer Docker Image - PR
    runs-on: ubuntu-latest
    needs: [generate-tag-name]
    env:
      TAG_NAME: ${{ needs.generate-tag-name.outputs.tag_name }}

    # Skip for the release pull requests
    if: startsWith(github.event.pull_request.head.ref, 'release/') != true && startsWith(github.event.pull_request.head.ref, 'hotfix-release/') != true
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PROD_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          load: true
          tags: |
            ${{ env.REPO_NAME }}:${{ env.TAG_NAME }}

      - name: Run Tests
        run: |
          docker run ${{ env.REPO_NAME }}:${{ env.TAG_NAME }} npm run test:ci

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          platforms: |
            linux/amd64
            linux/arm64

      - name: Build and Push Multi-platform Images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.REPO_NAME_OLD }}:${{ env.TAG_NAME }}
            ${{ env.REPO_NAME }}:${{ env.TAG_NAME }}
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            VERSION=${{ env.TAG_NAME }}
            COMMIT_HASH=${{ github.sha }}
  
  build-user-transformer-image:
    name: Build User Transformer Docker Image - PR
    runs-on: ubuntu-latest
    needs: [generate-tag-name]
    env:
      TAG_NAME: ${{ needs.generate-tag-name.outputs.tag_name }}

    # Skip for the release pull requests
    if: startsWith(github.event.pull_request.head.ref, 'release/') != true && startsWith(github.event.pull_request.head.ref, 'hotfix-release/') != true
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PROD_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: Dockerfile-ut-func
          load: true
          tags: |
            ${{ env.REPO_NAME }}:${{ env.TAG_NAME }}

      - name: Run Tests
        run: |
          docker run ${{ env.REPO_NAME }}:${{ env.TAG_NAME }} npm run test:ci

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          platforms: |
            linux/amd64
            linux/arm64

      - name: Build and Push Multi-platform Images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: Dockerfile-ut-func
          push: true
          tags: |
            ${{ env.REPO_NAME_OLD }}:${{ env.TAG_NAME }}
            ${{ env.REPO_NAME }}:${{ env.TAG_NAME }}
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            VERSION=${{ env.TAG_NAME }}
            COMMIT_HASH=${{ github.sha }}
